version: "3"
services:
  prom-spring-app:
    build: ./prom-spring-app
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - .\prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - .\custom.ini:/usr/share/grafana/conf/custom.ini
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:

